docker_builder:
  build_script:
    - "cat /etc/*-release"
    - "df -h"
    - "lscpu"
    - "free -m"
    - "apt-get install -y libyaml-libyaml-perl libtemplate-perl libio-handle-util-perl libio-all-perl libio-captureoutput-perl libjson-perl libpath-tiny-perl libstring-shellquote-perl libsort-versions-perl libdigest-sha-perl libdata-uuid-perl libdata-dump-perl libfile-copy-recursive-perl libfile-slurp-perl git runc"
    - "make nightly-linux-x86_64"
