release_linux_x86_64_gcc_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh gcc release linux x86_64"
    #- "make release-linux-x86_64"
    # Might try bumping the CPU count if there's a timeout issue.  Blocked by cirrus-ci-docs issue #741.
    # What is the CPU count limit?  "Linux Containers" docs say 8.0 CPU and 24 GB RAM; "FAQ" says 16.0 CPU.
    # Might try just building firefox by itself if there's a timeout issue.

release_linux_x86_64_firefox_docker_builder:
  timeout_in: 120m
  out_release_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_release_linux_x86_64"
    populate_script:
      - "mkdir -p out"
  git_release_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_release_linux_x86_64"
    populate_script:
      - "mkdir -p git_clones"
  depends_on:
    - "release_linux_x86_64_gcc"
  build_script:
    - "./tools/cirrus_build_project.sh firefox release linux x86_64"
