nightly_linux_x86_64_gcc_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh gcc nightly linux x86_64"

nightly_linux_x86_64_cmake_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh cmake nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_gcc"

nightly_linux_x86_64_https-everywhere_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh https-everywhere nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_cmake"

nightly_linux_x86_64_fonts_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh fonts nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_https-everywhere"

nightly_linux_x86_64_obfs4_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh obfs4 nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_fonts"

nightly_linux_x86_64_snowflake_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh snowflake nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_obfs4"

