nightly_linux_x86_64_download_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh release nightly linux x86_64 0"

nightly_linux_x86_64_gcc_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh gcc nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_download"

nightly_linux_x86_64_cmake_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh cmake nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_gcc"

nightly_linux_x86_64_https-everywhere_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh https-everywhere nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_cmake"

nightly_linux_x86_64_fonts_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh fonts nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_https-everywhere"

nightly_linux_x86_64_obfs4_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh obfs4 nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_fonts"

nightly_linux_x86_64_snowflake_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh snowflake nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_obfs4"

nightly_linux_x86_64_node_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh node nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_snowflake"

nightly_linux_x86_64_nasm_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh nasm nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_node"

nightly_linux_x86_64_clang-source_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh clang-source nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_nasm"

nightly_linux_x86_64_clang_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh clang nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_clang-source"

nightly_linux_x86_64_tor-launcher_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh tor-launcher nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_clang"

nightly_linux_x86_64_openssl_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh openssl nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_tor-launcher"

nightly_linux_x86_64_libevent_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p git_clones"
  git_nightly_linux_x86_64_fonts_cache:
    folder: fonts
    fingerprint_script:
      - "echo git_nightly_linux_x86_64_fonts"
    reupload_on_changes: true
    populate_script:
      - "mkdir -p fonts"
  build_script:
    - "./tools/cirrus_build_project.sh libevent nightly linux x86_64 1"
  depends_on:
    - "nightly_linux_x86_64_openssl"

