nightly_linux_x86_64_gcc_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh gcc nightly linux x86_64"

nightly_linux_x86_64_rust_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh rust nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_gcc"

nightly_linux_x86_64_firefox_docker_builder:
  timeout_in: 120m
  out_nightly_linux_x86_64_cache:
    folder: out
    fingerprint_script:
      - "echo out_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p out"
  git_nightly_linux_x86_64_cache:
    folder: git_clones
    fingerprint_script:
      - "echo git_nightly_linux_x86_64"
    populate_script:
      - "mkdir -p git_clones"
  build_script:
    - "./tools/cirrus_build_project.sh firefox nightly linux x86_64"
  depends_on:
    - "nightly_linux_x86_64_rust"

