#!/bin/bash
[% c("var/set_default_env") -%]
tar xf [% project %]-[% c("version") %].tar.gz
mv [% project %]-[% c("version") %] clang-source
[% c('tar', {
        tar_src => [ 'clang-source' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
