#!/bin/bash
[% c("var/set_default_env") -%]
unzip -qq [% c("input_files_by_name/gradle") %]
mv [% project %]-[% c("var/gradle_version") %] [% project %]
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
